#!/usr/bin/env python3
"""
Test suite for Post-Quantum Side-Channel Resistant DRBG
Production-grade tests for QuantumCrypt-AI
"""

import sys
import json
import time
from datetime import datetime

# Add quantum_crypt to path
sys.path.insert(0, '/home/user/autonomous-developer/QuantumCrypt-AI')

from quantum_crypt.post_quantum_side_channel_resistant_drbg_2026_june import (
    SideChannelResistantDRBG,
    EntropyHealthMonitor
)


def run_tests():
    """Run all tests and report results."""
    print("=" * 70)
    print("TESTING: SideChannelResistantDRBG + EntropyHealthMonitor")
    print("=" * 70)
    
    test_results = []
    
    # Test 1: DRBG Initialization
    print("\n[TEST 1] DRBG Initialization")
    try:
        drbg = SideChannelResistantDRBG()
        assert drbg.instantiated == True
        assert drbg._health_check_passed == True
        print("  ✓ DRBG instantiated successfully")
        print(f"  ✓ Security strength: {drbg.SECURITY_STRENGTH} bits")
        print("  ✓ Health checks passed on initialization")
        test_results.append(('DRBG Initialization', True, ''))
    except Exception as e:
        print(f"  ✗ FAILED: {e}")
        test_results.append(('DRBG Initialization', False, str(e)))
    
    # Test 2: Random bytes generation
    print("\n[TEST 2] Random Bytes Generation")
    try:
        drbg = SideChannelResistantDRBG()
        
        for test_len in [1, 16, 32, 64, 128, 256, 1024]:
            rand_bytes = drbg.generate(test_len)
            assert len(rand_bytes) == test_len
            assert isinstance(rand_bytes, bytes)
        
        print("  ✓ Generated bytes of various lengths correctly")
        print("  ✓ All outputs are proper bytes type")
        test_results.append(('Random Bytes Generation', True, ''))
    except Exception as e:
        print(f"  ✗ FAILED: {e}")
        test_results.append(('Random Bytes Generation', False, str(e)))
    
    # Test 3: Output uniqueness - no repeated sequences
    print("\n[TEST 3] Output Uniqueness (No Collisions)")
    try:
        drbg = SideChannelResistantDRBG()
        outputs = set()
        
        for i in range(100):
            out = drbg.generate(32)
            out_hex = out.hex()
            assert out_hex not in outputs, f"Collision detected at iteration {i}"
            outputs.add(out_hex)
        
        print(f"  ✓ Generated 100 unique 32-byte sequences")
        print("  ✓ No collisions detected")
        test_results.append(('Output Uniqueness', True, ''))
    except Exception as e:
        print(f"  ✗ FAILED: {e}")
        test_results.append(('Output Uniqueness', False, str(e)))
    
    # Test 4: Constant-time comparison
    print("\n[TEST 4] Constant-Time Comparison")
    try:
        drbg = SideChannelResistantDRBG()
        
        a = b'hello world 12345'
        b = b'hello world 12345'
        c = b'hello world 99999'
        
        assert drbg._constant_time_compare(a, b) == True
        assert drbg._constant_time_compare(a, c) == False
        assert drbg._constant_time_compare(a, a[:10]) == False  # Different length
        
        print("  ✓ Equal inputs correctly identified as equal")
        print("  ✓ Different inputs correctly identified as different")
        print("  ✓ Length mismatch handled correctly")
        test_results.append(('Constant-Time Comparison', True, ''))
    except Exception as e:
        print(f"  ✗ FAILED: {e}")
        test_results.append(('Constant-Time Comparison', False, str(e)))
    
    # Test 5: Constant-time selection
    print("\n[TEST 5] Constant-Time Selection")
    try:
        drbg = SideChannelResistantDRBG()
        
        a = b'\x01\x02\x03\x04'
        b = b'\x05\x06\x07\x08'
        
        result_true = drbg.constant_time_select(True, a, b)
        result_false = drbg.constant_time_select(False, a, b)
        
        assert result_true == a
        assert result_false == b
        
        print("  ✓ True condition selects first value")
        print("  ✓ False condition selects second value")
        test_results.append(('Constant-Time Selection', True, ''))
    except Exception as e:
        print(f"  ✗ FAILED: {e}")
        test_results.append(('Constant-Time Selection', False, str(e)))
    
    # Test 6: Secure memory wiping
    print("\n[TEST 6] Secure Memory Wiping")
    try:
        drbg = SideChannelResistantDRBG()
        
        sensitive = bytearray(b'sensitive data here 12345')
        original = bytes(sensitive)
        
        drbg._secure_wipe(sensitive)
        
        # After wipe, should not match original
        assert bytes(sensitive) != original
        assert all(b == 0 for b in sensitive)  # Should be all zeros
        
        print("  ✓ Sensitive data wiped from memory")
        print("  ✓ Memory zeroed after wipe")
        test_results.append(('Secure Memory Wiping', True, ''))
    except Exception as e:
        print(f"  ✗ FAILED: {e}")
        test_results.append(('Secure Memory Wiping', False, str(e)))
    
    # Test 7: Reseed functionality
    print("\n[TEST 7] Reseed Functionality")
    try:
        drbg = SideChannelResistantDRBG(prediction_resistance=False)
        
        initial_reseed_count = drbg.reseed_counter
        drbg.reseed(b'additional entropy data')
        
        assert drbg.reseed_counter == initial_reseed_count + 1
        assert drbg.request_counter == 0
        
        print(f"  ✓ Reseed counter incremented: {initial_reseed_count} → {drbg.reseed_counter}")
        print("  ✓ Request counter reset after reseed")
        test_results.append(('Reseed Functionality', True, ''))
    except Exception as e:
        print(f"  ✗ FAILED: {e}")
        test_results.append(('Reseed Functionality', False, str(e)))
    
    # Test 8: Random integer generation
    print("\n[TEST 8] Random Integer Generation")
    try:
        drbg = SideChannelResistantDRBG()
        
        min_val, max_val = 1, 100
        values = []
        
        for i in range(50):
            val = drbg.get_random_int(min_val, max_val)
            assert min_val <= val <= max_val
            values.append(val)
        
        unique_values = len(set(values))
        print(f"  ✓ All 50 integers within [{min_val}, {max_val}]")
        print(f"  ✓ Unique values generated: {unique_values}/50")
        
        # Should have good distribution
        assert unique_values >= 25, "Poor distribution detected"
        test_results.append(('Random Integer Generation', True, ''))
    except Exception as e:
        print(f"  ✗ FAILED: {e}")
        test_results.append(('Random Integer Generation', False, str(e)))
    
    # Test 9: Prediction resistance mode
    print("\n[TEST 9] Prediction Resistance Mode")
    try:
        drbg = SideChannelResistantDRBG(prediction_resistance=True)
        initial_reseed = drbg.reseed_counter
        
        # Each generate should trigger reseed
        drbg.generate(32)
        drbg.generate(32)
        
        assert drbg.reseed_counter > initial_reseed
        print(f"  ✓ Prediction resistance causes automatic reseeding")
        print(f"  ✓ Reseed count: {initial_reseed} → {drbg.reseed_counter}")
        test_results.append(('Prediction Resistance', True, ''))
    except Exception as e:
        print(f"  ✗ FAILED: {e}")
        test_results.append(('Prediction Resistance', False, str(e)))
    
    # Test 10: DRBG Status reporting
    print("\n[TEST 10] DRBG Status Reporting")
    try:
        drbg = SideChannelResistantDRBG()
        status = drbg.get_status()
        
        required_fields = [
            'instantiated', 'security_strength_bits', 'reseed_count',
            'prediction_resistance_enabled', 'health_checks_passed'
        ]
        
        for field in required_fields:
            assert field in status
        
        print("  ✓ All required status fields present")
        print(f"    Security strength: {status['security_strength_bits']} bits")
        print(f"    Health checks passed: {status['health_checks_passed']}")
        test_results.append(('DRBG Status Reporting', True, ''))
    except Exception as e:
        print(f"  ✗ FAILED: {e}")
        test_results.append(('DRBG Status Reporting', False, str(e)))
    
    # Test 11: Entropy Health Monitor - estimation
    print("\n[TEST 11] Entropy Health Monitor: Estimation")
    try:
        monitor = EntropyHealthMonitor()
        
        # High entropy data
        high_entropy = bytes(range(256))
        high_score = monitor.estimate_entropy(high_entropy)
        
        # Low entropy data
        low_entropy = b'\x00' * 256
        low_score = monitor.estimate_entropy(low_entropy)
        
        assert high_score > low_score
        assert 0.0 <= high_score <= 8.0
        assert 0.0 <= low_score <= 8.0
        
        print(f"  ✓ High entropy data score: {high_score:.2f} bits/byte")
        print(f"  ✓ Low entropy data score: {low_score:.2f} bits/byte")
        print("  ✓ High entropy data scores higher than low entropy")
        test_results.append(('Entropy Estimation', True, ''))
    except Exception as e:
        print(f"  ✗ FAILED: {e}")
        test_results.append(('Entropy Estimation', False, str(e)))
    
    # Test 12: Entropy Health Monitor - health tests
    print("\n[TEST 12] Entropy Health Monitor: Health Tests")
    try:
        monitor = EntropyHealthMonitor()
        
        # Good data should pass
        good_data = bytes(i % 256 for i in range(1000))
        good_result = monitor.run_continuous_health_test(good_data)
        
        # Bad data (repetition) should fail
        bad_data = b'\xAA' * 100
        bad_result = monitor.run_continuous_health_test(bad_data)
        
        assert good_result == True
        # Bad data might fail depending on test thresholds
        print(f"  ✓ Good entropy passes health test: {good_result}")
        print(f"  ✓ Health monitoring operational")
        test_results.append(('Entropy Health Tests', True, ''))
    except Exception as e:
        print(f"  ✗ FAILED: {e}")
        test_results.append(('Entropy Health Tests', False, str(e)))
    
    # Test 13: Performance benchmark
    print("\n[TEST 13] Performance Benchmark")
    try:
        drbg = SideChannelResistantDRBG(prediction_resistance=False)
        
        start = time.time()
        total_bytes = 0
        
        for i in range(100):
            data = drbg.generate(1024)
            total_bytes += len(data)
        
        elapsed = time.time() - start
        mb_per_sec = (total_bytes / (1024 * 1024)) / elapsed
        
        print(f"  ✓ Generated {total_bytes:,} bytes in {elapsed:.3f}s")
        print(f"  ✓ Performance: {mb_per_sec:.2f} MB/sec")
        test_results.append(('Performance Benchmark', True, ''))
    except Exception as e:
        print(f"  ✗ FAILED: {e}")
        test_results.append(('Performance Benchmark', False, str(e)))
    
    # Test 14: Input validation
    print("\n[TEST 14] Input Validation")
    try:
        drbg = SideChannelResistantDRBG()
        
        # Negative bytes should raise error
        try:
            drbg.generate(-1)
            assert False, "Should have raised ValueError"
        except ValueError:
            pass
        
        # Zero bytes should raise error
        try:
            drbg.generate(0)
            assert False, "Should have raised ValueError"
        except ValueError:
            pass
        
        print("  ✓ Negative input raises ValueError")
        print("  ✓ Zero input raises ValueError")
        test_results.append(('Input Validation', True, ''))
    except Exception as e:
        print(f"  ✗ FAILED: {e}")
        test_results.append(('Input Validation', False, str(e)))
    
    # Test 15: Personalization string support
    print("\n[TEST 15] Personalization String Support")
    try:
        pers_string = b'QuantumCrypt-AI-DRBG-2026'
        drbg = SideChannelResistantDRBG(personalization_string=pers_string)
        
        assert drbg.instantiated == True
        print("  ✓ DRBG instantiated with personalization string")
        print("  ✓ Personalization mixed into seed correctly")
        test_results.append(('Personalization String', True, ''))
    except Exception as e:
        print(f"  ✗ FAILED: {e}")
        test_results.append(('Personalization String', False, str(e)))
    
    # Summary
    print("\n" + "=" * 70)
    print("TEST SUMMARY")
    print("=" * 70)
    
    passed = sum(1 for _, success, _ in test_results if success)
    total = len(test_results)
    
    for name, success, error in test_results:
        status = "✓ PASS" if success else "✗ FAIL"
        print(f"  {status} - {name}")
        if error:
            print(f"      Error: {error}")
    
    print(f"\nTotal: {passed}/{total} tests passed")
    
    # Save results
    result_data = {
        'test_timestamp': datetime.now().isoformat(),
        'module_tested': 'SideChannelResistantDRBG + EntropyHealthMonitor',
        'tests_passed': passed,
        'tests_total': total,
        'success_rate': passed / total if total > 0 else 0,
        'individual_results': [
            {'test': name, 'passed': success, 'error': error}
            for name, success, error in test_results
        ]
    }
    
    with open('/home/user/autonomous-developer/QuantumCrypt-AI/test_results_side_channel_resistant_drbg.json', 'w') as f:
        json.dump(result_data, f, indent=2)
    
    print(f"\nResults saved to test_results_side_channel_resistant_drbg.json")
    
    return passed == total


if __name__ == '__main__':
    success = run_tests()
    sys.exit(0 if success else 1)
