"""
Test Suite for QRNG Entropy Collector
Dimension A: Feature Expansion
Version: v23 - June 2026

Tests cover:
- Basic random byte generation
- Integer generation with uniform distribution
- UUID generation
- Entropy source health checks
- Pool management and reseeding
- Statistics tracking
- Custom source integration
- Thread safety
"""

import unittest
import threading
import uuid
from collections import Counter

from quantum_crypt.feature_expansion_qrng_entropy_collector_v23_2026_june import (
    EntropySample,
    EntropySource,
    EntropySourceType,
    HealthStatus,
    QRNGEntropyCollector,
    SystemEntropySource,
    TimingJitterSource,
    SecretsSource,
)


class TestEntropySample(unittest.TestCase):
    """Tests for EntropySample dataclass."""

    def test_sample_creation(self):
        sample = EntropySample(b'\x00\x01\x02\x03', EntropySourceType.SYSTEM)
        self.assertEqual(len(sample.data), 4)
        self.assertEqual(sample.source_type, EntropySourceType.SYSTEM)
        self.assertIsNotNone(sample.sample_id)

    def test_entropy_estimation(self):
        # High entropy data
        high_entropy = bytes(range(256))
        sample = EntropySample(high_entropy, EntropySourceType.SYSTEM)
        self.assertGreater(sample.estimated_entropy, 0)

    def test_empty_sample(self):
        sample = EntropySample(b'', EntropySourceType.SYSTEM)
        self.assertEqual(sample.estimated_entropy, 0.0)


class TestSystemEntropySource(unittest.TestCase):
    """Tests for SystemEntropySource."""

    def test_get_sample(self):
        source = SystemEntropySource()
        sample = source.get_sample(32)
        self.assertIsNotNone(sample)
        self.assertEqual(len(sample.data), 32)
        self.assertEqual(sample.source_type, EntropySourceType.SYSTEM)

    def test_health_check(self):
        source = SystemEntropySource()
        status = source.health_check()
        self.assertIn(status, [HealthStatus.HEALTHY, HealthStatus.DEGRADED])


class TestTimingJitterSource(unittest.TestCase):
    """Tests for TimingJitterSource."""

    def test_get_sample(self):
        source = TimingJitterSource(iterations=100)
        sample = source.get_sample(16)
        self.assertIsNotNone(sample)
        self.assertEqual(len(sample.data), 16)

    def test_health_check(self):
        source = TimingJitterSource(iterations=100)
        status = source.health_check()
        self.assertIn(status, [HealthStatus.HEALTHY, HealthStatus.DEGRADED])


class TestSecretsSource(unittest.TestCase):
    """Tests for SecretsSource."""

    def test_get_sample(self):
        source = SecretsSource()
        sample = source.get_sample(64)
        self.assertIsNotNone(sample)
        self.assertEqual(len(sample.data), 64)

    def test_health_check(self):
        source = SecretsSource()
        status = source.health_check()
        self.assertIn(status, [HealthStatus.HEALTHY, HealthStatus.DEGRADED])


class TestQRNGEntropyCollector(unittest.TestCase):
    """Main test suite for QRNGEntropyCollector."""

    def setUp(self):
        self.collector = QRNGEntropyCollector(min_pool_size=1024)

    def test_initialization(self):
        stats = self.collector.get_statistics()
        self.assertEqual(stats["total_bytes_generated"], 0)
        self.assertEqual(stats["reseed_count"], 0)

    def test_get_random_bytes_basic(self):
        result = self.collector.get_random_bytes(32)
        self.assertEqual(len(result), 32)
        self.assertIsInstance(result, bytes)

    def test_get_random_bytes_zero(self):
        result = self.collector.get_random_bytes(0)
        self.assertEqual(result, b'')

    def test_get_random_bytes_negative(self):
        result = self.collector.get_random_bytes(-10)
        self.assertEqual(result, b'')

    def test_get_random_bytes_large(self):
        result = self.collector.get_random_bytes(1024)
        self.assertEqual(len(result), 1024)

    def test_random_bytes_uniqueness(self):
        # Generated bytes should be unique (very high probability)
        results = set()
        for _ in range(100):
            results.add(self.collector.get_random_bytes(8))
        # With 64 bits, collision chance is negligible
        self.assertEqual(len(results), 100)

    def test_get_random_int_range(self):
        min_val = 10
        max_val = 20
        for _ in range(100):
            value = self.collector.get_random_int(min_val, max_val)
            self.assertGreaterEqual(value, min_val)
            self.assertLessEqual(value, max_val)

    def test_get_random_int_equal_bounds(self):
        value = self.collector.get_random_int(5, 5)
        self.assertEqual(value, 5)

    def test_get_random_int_distribution(self):
        # Test uniform distribution (rough check)
        counts = Counter()
        trials = 10000
        for _ in range(trials):
            counts[self.collector.get_random_int(0, 9)] += 1
        
        # Each value should appear roughly 1000 times
        expected = trials // 10
        for count in counts.values():
            # Allow 20% tolerance
            self.assertGreater(count, expected * 0.8)
            self.assertLess(count, expected * 1.2)

    def test_get_random_bounded(self):
        for _ in range(100):
            value = self.collector.get_random_bounded(100)
            self.assertGreaterEqual(value, 0)
            self.assertLess(value, 100)

    def test_get_random_uuid(self):
        generated_uuid = self.collector.get_random_uuid()
        self.assertIsInstance(generated_uuid, uuid.UUID)
        self.assertEqual(generated_uuid.version, 4)  # UUID v4

    def test_uuid_uniqueness(self):
        uuids = set()
        for _ in range(100):
            uuids.add(self.collector.get_random_uuid())
        self.assertEqual(len(uuids), 100)

    def test_run_health_checks(self):
        results = self.collector.run_health_checks()
        self.assertIsInstance(results, dict)
        # Should have results for each source
        self.assertGreaterEqual(len(results), 3)

    def test_get_statistics(self):
        # Generate some random data first
        self.collector.get_random_bytes(100)
        
        stats = self.collector.get_statistics()
        self.assertIn("pool_size_bytes", stats)
        self.assertIn("pool_entropy_bits", stats)
        self.assertIn("total_bytes_generated", stats)
        self.assertIn("sources", stats)
        self.assertGreater(stats["total_bytes_generated"], 0)

    def test_mix_external_entropy(self):
        initial_stats = self.collector.get_statistics()
        initial_entropy = initial_stats["pool_entropy_bits"]
        
        self.collector.mix_external_entropy(b"external entropy data", 128.0)
        
        new_stats = self.collector.get_statistics()
        self.assertGreaterEqual(new_stats["pool_entropy_bits"], initial_entropy)

    def test_generate_seed(self):
        seed = self.collector.generate_seed(256)
        self.assertEqual(len(seed), 32)  # 256 bits = 32 bytes

    def test_generate_seed_custom_size(self):
        seed = self.collector.generate_seed(128)
        self.assertEqual(len(seed), 16)

    def test_get_random_string_default(self):
        result = self.collector.get_random_string(20)
        self.assertEqual(len(result), 20)
        # Default charset is alphanumeric
        self.assertTrue(all(c.isalnum() for c in result))

    def test_get_random_string_custom_charset(self):
        charset = "ABCDEF"
        result = self.collector.get_random_string(50, charset)
        self.assertEqual(len(result), 50)
        self.assertTrue(all(c in charset for c in result))

    def test_get_random_string_empty(self):
        result = self.collector.get_random_string(0)
        self.assertEqual(result, "")

    def test_add_custom_source(self):
        class CustomSource(EntropySource):
            def __init__(self):
                super().__init__(EntropySourceType.EXTERNAL, "custom_test")
            
            def get_sample(self, num_bytes):
                import os
                return EntropySample(os.urandom(num_bytes), self.source_type)

        custom_source = CustomSource()
        initial_count = len(self.collector.get_statistics()["sources"])
        self.collector.add_custom_source(custom_source)
        new_count = len(self.collector.get_statistics()["sources"])
        self.assertEqual(new_count, initial_count + 1)

    def test_reseed_on_demand(self):
        # Force multiple reseeds by requesting lots of randomness
        for _ in range(10):
            self.collector.get_random_bytes(512)
        
        stats = self.collector.get_statistics()
        self.assertGreater(stats["reseed_count"], 0)

    def test_thread_safety(self):
        """Test that collector works correctly from multiple threads."""
        results = []
        errors = []
        
        def worker():
            try:
                for _ in range(50):
                    r = self.collector.get_random_bytes(16)
                    results.append(r)
            except Exception as e:
                errors.append(e)

        threads = [threading.Thread(target=worker) for _ in range(5)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()

        self.assertEqual(len(errors), 0)
        self.assertEqual(len(results), 250)

    def test_byte_distribution(self):
        """Rough check that bytes are reasonably distributed."""
        data = self.collector.get_random_bytes(10000)
        counts = Counter(data)
        
        # Each byte value should appear at least some times
        # With 10000 bytes, average is ~39 per value
        for byte_val in range(256):
            # Just check no byte is completely missing (highly unlikely)
            # This is a sanity check, not a strict statistical test
            pass
        
        # At least most bytes should appear
        non_zero = sum(1 for c in counts.values() if c > 0)
        self.assertGreater(non_zero, 200)


class TestEntropyCollectorIntegration(unittest.TestCase):
    """Integration tests for the entropy collector."""

    def test_continuous_operation(self):
        """Test extended operation."""
        collector = QRNGEntropyCollector()
        
        total_bytes = 0
        for i in range(100):
            data = collector.get_random_bytes(64)
            total_bytes += len(data)
            self.assertEqual(len(data), 64)
        
        stats = collector.get_statistics()
        self.assertEqual(stats["total_bytes_generated"], total_bytes)

    def test_health_check_during_operation(self):
        collector = QRNGEntropyCollector(auto_health_check=True)
        
        # Generate some data (auto health checks should run)
        for _ in range(10):
            collector.get_random_bytes(32)
        
        # Explicit health check
        results = collector.run_health_checks()
        self.assertGreater(len(results), 0)


if __name__ == "__main__":
    unittest.main(verbosity=2)
